/** DocExtract design system — tokens ported from the Stitch export. */
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#96a6b9",
        "on-primary-fixed-variant": "#294678",
        "on-error-container": "#93000a",
        "outline-variant": "#c4c6d0",
        "surface-dim": "#d8dadd",
        primary: "#002452",
        "tertiary-fixed": "#d3e4f8",
        outline: "#747780",
        secondary: "#0051d5",
        "inverse-primary": "#acc7ff",
        "on-background": "#191c1e",
        "error-container": "#ffdad6",
        "secondary-container": "#316bf3",
        "on-tertiary-fixed": "#0c1d2b",
        "status-success": "#15803D",
        "text-primary": "#1A2433",
        "inverse-on-surface": "#eff1f4",
        "status-review": "#1D4ED8",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e6e8eb",
        "on-secondary-fixed-variant": "#003ea8",
        "status-neutral": "#64748B",
        "surface-variant": "#e0e3e6",
        "status-error": "#B91C1C",
        "surface-white": "#FFFFFF",
        "on-surface-variant": "#44474f",
        "primary-container": "#1b3a6b",
        "surface-bright": "#f7f9fc",
        surface: "#f7f9fc",
        "secondary-fixed-dim": "#b4c5ff",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e6",
        error: "#ba1a1a",
        "primary-fixed": "#d7e2ff",
        "on-primary-fixed": "#001a40",
        "on-tertiary-fixed-variant": "#394858",
        "on-primary-container": "#89a5dd",
        "on-secondary-fixed": "#00174b",
        "surface-container-low": "#f2f4f7",
        "border-base": "#E3E8EF",
        "secondary-fixed": "#dbe1ff",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-tint": "#425e91",
        "tertiary-container": "#2c3c4b",
        "on-secondary-container": "#fefcff",
        "primary-fixed-dim": "#acc7ff",
        "status-warning": "#B45309",
        "surface-container": "#eceef1",
        background: "#f7f9fc",
        tertiary: "#162635",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#b8c8dc",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "topbar-height": "64px",
        "stack-sm": "8px",
        "stack-lg": "24px",
        gutter: "24px",
        "sidebar-width": "260px",
        "stack-md": "16px",
      },
      fontFamily: {
        display: ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        display: ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "mono-data": ["13px", { lineHeight: "20px", fontWeight: "450" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
